% Leaf information
function info = Tree_descriptions(species)
information = {...
'Acer negundo', 'Box elder or Maple ash: Various uses, sap is edible (often used to make candy), dry scrapings of the inner bark can be boiled until sugar crystallizes out of it and eaten.  A decoction of the inner bark can be used as an emetic.';...
'Acer saccharum', 'Sugar maple: Sap used to make maple syrup';...
'Acer saccharinum', 'Silver maple: Sap can be used to make sugar.  An infusion of bark from the south side of the tree can be used as a cough medicine';...
'Aesculus hipposcasanum', 'Horse-chestunt or Conker tree:  Extract from the seeds is used as an anti-inflammatory';...
'Ailanthus altissima', 'Tree of heaven: Dried bark has numerous medicinal properties used to treat dysentery and hemorrages.  The leaves can be used to treat boils, abscesses, and itches';...
'Amelanchier arborea', 'Downy Serviceberry.  Fruit is edible, often used to make pie and jam';...
'Amelanchier Canadensis', 'Canadian serviceberry: fruit is edible, tea made from root bark used to treat excessive menstrual cramps and diarrhea.';...
'Amelnchier laevis', 'Smooth shadbush or Allegheny serviceberry: fruit is edible raw or cooked, bark made into herbal medicine for expectant mothers';...
'Asimina triloba', 'Pawpaw: fruit is edible';...
'Broussonetia papyifera', 'Paper mulberry: fruit and cooked leaves are edible';...
'Carya ovata', 'Shagbark hickory: nuts are edible';...
'Carya tomentosa', 'Mockernut hickory: nuts are edible';...
'Castanea dentate', 'American chestnut: (chestnuts) nuts are edible, used to treat whooping cough and heart conditions';...
'Celtis occidentalis', 'Common huckleberry: (huckleberries) berries are edible (remarkably high in calories, carbohydrates, and protein) raw and cooked';...
'Celtis tenuifolia', 'Dwarf huckleberry: fruit is edible';...
'Cercis Canadensis', 'Eastern redbud: flowers can be eaten raw or boiled, seeds can be eaten roasted';...
'Chionanthus virginicus', 'White fringetree: dried roots and bark used to treat skin inflammations, crushed bark used to treat sores and wounds';...
'Cornus kousa', 'Japanese dogwood: berries are edible';...
'Cornus mas', 'Cornelian cherry: fruit is edible';...
'Corylus colurna', 'Turkish hazel: nuts are edible';...
'Crataegus phaenopyrum', 'Washington hawthorn: fruit is edible raw or cooked';...
'Diospyros virginiana', 'American persimmon: (persimmon) fruit is edible';...
'Fagus gradifolia', 'American beech: nuts are edible';...
'Ficus carica', 'Common fig tree: (figs) fruit is edible';...
'Ginkgo biloba', 'Ginko: Nuts area edible, however, eaten in large quantities over long time period can cause poisoning';...
'Gleditsia triacanthos', 'Honey locust: legumes are edible';...
'Gymnocladus dioicus', 'Kentucky coffeetree: seeds can be eaten, but must be roasted.  Used as a substitute for coffee.';...
'Juglans nigra', 'Eastern black walnut: nuts are edible';...
'Malus angustifolia', 'Southern crabapple: fruit is edible but is usually cooked into jams because it is very bitter when raw.';...
'Malus baccata', 'Wild apple: fruits are edible, can be eaten dried';...
'Malus pumila', 'Apple tree: apples, are edible';...
'Morus alba', 'White mulberry: berries are edible, root bark used against food-poisoning, also used to treat fever, headache, and sore eyes';...
'Morus rubra', 'Red mulberry: berries are edible';...
'Phellodendron amurense', 'Amur cork tree: used orally to treat abdominal pain, diarrhea, gastroenteritis, and urinary tract infections';...
'Prunus pensylvanica', 'Bird cherry, pin cherry: fruit is edible';...
'Prunus serotine', 'Black cherry: (black cherries) fruit is edible';...
'Prunus virginiana', 'Chokecherry: fruit is edible but bitter, root bark made into a concoction used to ward off and treats colds, fever, and stomach maladies.  Plant is toxic to horses, cattle, etc';...
'Quercus muehlenberger', 'Chinkapin oak: nuts inside of the shell are edible, can be eaten raw';...
'Quercus virginiana', 'Southern live oak: cooking oil can be extracted from the acorns, roots can be cooked like potatoes';...
'Robinia pseudoacacia', 'Black locust: flowers can be eaten, seeds and pods are edible raw and boiled.  Leaves and bark are toxic.';...
'Salix nigra', 'Black willow: willow roots have been used to treat malaria, bark contains a chemical similar to asprin and can be used to treat fever, headache, and coughs';...
'Sassafras albidum', 'Sassafras: used as a flavoring in many foods, also used to treat wounds, urinary disorders, and high fevers';...
'Tilia americana', 'American basswood, American linden: flowers and leaves are edible. flowers used in colds, cough, fever, infections, inflammation, high blood pressure, headache, as a diuretic, as an antispasmodic, and as a sedative. Wood is used for liver and gallbladder disorders.'...
};

k = strfind(information,species);
ind = find(~cellfun(@isempty,k));
if isempty(ind)
    info = 'DO NOT EAT!!! YOU WILL PROBABLY DIE!!';
else
    info = information{ind,2};
end
